#lang s-exp sonic-pi/lsonic

;; run every synth that has been defined.
;; if any one synth sounds off (as compared to Sonic Pi 65)
;; then I have messed up the args, most likely the ADSR
(note 'dull_bell 65)
(psleep 2)
(note 'pretty_bell 65)
(psleep 2)
(note 'beep 65)
(psleep 2)
(note 'saw 65)
(psleep 2)
(note 'square 65)
(psleep 2)
(note 'pulse 65)
(psleep 2)
(note 'subpulse 65)
(psleep 2)
(note 'tri 65)
(psleep 2)
(note 'dsaw 65)
(psleep 2)
(note 'dtri 65)
(psleep 2)
(note 'dpulse 65)
(psleep 2)
(note 'fm 65)
(psleep 2)
(note 'mod_fm 65)
(psleep 2)
(note 'mod_saw 65)
(psleep 2)
(note 'mod_dsaw 65)
(psleep 2)
(note 'mod_sine 65)
(psleep 2)
(note 'mod_tri 65)
(psleep 2)
(note 'mod_pulse 65)
(psleep 2)
(note 'tb303 65)
(psleep 2)
(note 'supersaw 65)
(psleep 2)
(note 'hoover 65)
(psleep 2)
(note 'synth_violin 65)
(psleep 2)
(note 'pluck 65)
(psleep 2)
(note 'piano 65)
(psleep 2)
(note 'growl 65)
(psleep 2)
(note 'dark_ambience 65)
(psleep 2)
(note 'hollow 65)
(psleep 2)
(note 'zawa 65)
(psleep 2)
(note 'prophet 65)
(psleep 2)
(note 'chiplead 65)
(psleep 2)
(note 'chipbass 65)
(psleep 2)
(note 'noise 65)
(psleep 2)
(note 'gnoise 65)
(psleep 2)
(note 'bnoise 65)
(psleep 2)
(note 'pnoise 65)
(psleep 2)
(note 'cnoise 65)
(psleep 2)
(note 'chipnoise 65)
(psleep 2)
(note 'tech_saws 65)